version: '3'
services:
  payarawat:
    build: ./images/payara
    environment:
     - ADMIN_PASSWORD=admin
    links:
      - db:db
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - 'phpmyadmin'
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: gamification
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - 'default'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8090:80"
    depends_on:
      - 'db'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test